# Generated by Django 5.2.8 on 2026-01-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок записи")),
                ("content", models.CharField(max_length=1000, verbose_name="Содержимое записи")),
                (
                    "preview",
                    models.ImageField(blank=True, null=True, upload_to="blog/image", verbose_name="Превью записи"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания записи")),
                ("publication_flag", models.BooleanField(default=False, verbose_name="Признак публикации")),
                (
                    "views_counter",
                    models.PositiveIntegerField(
                        default=0, help_text="Укажите количество просмотров", verbose_name="Счетчик просмотров"
                    ),
                ),
            ],
            options={
                "verbose_name": "Заголовок записи",
                "verbose_name_plural": "Заголовки записей",
                "ordering": ["title", "publication_flag", "created_at", "views_counter"],
            },
        ),
    ]
