# Generated by Django 4.2.2 on 2026-01-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_views_counter"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "category", "price", "created_at", "updated_at"],
                "permissions": [("can_unpublish_product", "Can edit publication flag")],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="publication_flag",
            field=models.BooleanField(default=False, verbose_name="Признак публикации"),
        ),
    ]
